# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_STAFF:       ROLE_USER
        ROLE_ADMIN:       [ROLE_STAFF, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

#    role_hierarchy:
#        ROLE_MODERATOR:       ROLE_USER
#        ROLE_AGENT:      ROLE_USER
#        ROLE_SUPPORT:    ROLE_USER
#        ROLE_ADMIN:      ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_SHOP,ROLE_AGENT,ROLE_SUPPORT,ROLE_ADMIN,ROLE_SUPER_ADMIN]}

# ＢＡＳＩＣ認証するとき、.htaccessを使う方が良い
# admin/admin
#security:
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: 'admin'
#                        roles: 'ROLE_ADMIN'
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~
#            http_basic: ~
#
#    access_control:
#        - { path: ^/, roles: ROLE_ADMIN }
#
#    encoders:
#        Symfony\Component\Security\Core\User\User:
#            algorithm: plaintext
    acl:
        connection: default
